## Lift all PredRet docker images
# docker run --name predret-mongo -v $PWD/datadir:/data/db -p 27017:27017 -d mongo:latest

predret-mongo:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - /vol/phenomenal/src/docker/MetabolitDB/datadir:/data/db


# - docker run -d --link predret-mongo:predret-mongo -p 8788:3838 sneumann/predret:snapshot 
predret-shiny:
  image: sneumann/predret:snapshot
  ports:
    - 8788:3838
  links:
    - predret-mongo




